### Sorting Data

In [1]:
import pandas as pd

In [2]:
people = {
    "first" : ["Vijay", "Abhishek", "Ravi", "Anand", "John", "Shivam", "Neeraj", "Shivansh", "Akash", "Saurabh"],
    "last" : ["Yadav", "Yadav", "Singh", "Pal", "Doe", "Bind", "Yadav", "Singh", "Singh", "Maurya"],
    "email" : ["vijay@gmail.com", "abhi@gmail.com", "ravi@gmail.com", "anand@gmail.com", "john@gmail.com", "shivam@gmail.com", "neeraj@gmail.com", "shiv@gmail.com", "akash@gmail.com", "saurabh@gmail.com"],
    "qualification" : ["BSc", "BCA", "B.A.", "B.Tech", "M.Tech", "M.A.", "BSc", "BCA", "LLB", "BCA"]
}

In [3]:
df = pd.DataFrame(people)

In [4]:
df

      first    last              email qualification
0     Vijay   Yadav    vijay@gmail.com           BSc
1  Abhishek   Yadav     abhi@gmail.com           BCA
2      Ravi   Singh     ravi@gmail.com          B.A.
3     Anand     Pal    anand@gmail.com        B.Tech
4      John     Doe     john@gmail.com        M.Tech
5    Shivam    Bind   shivam@gmail.com          M.A.
6    Neeraj   Yadav   neeraj@gmail.com           BSc
7  Shivansh   Singh     shiv@gmail.com           BCA
8     Akash   Singh    akash@gmail.com           LLB
9   Saurabh  Maurya  saurabh@gmail.com           BCA

In [5]:
df.sort_values(by='first')

      first    last              email qualification
1  Abhishek   Yadav     abhi@gmail.com           BCA
8     Akash   Singh    akash@gmail.com           LLB
3     Anand     Pal    anand@gmail.com        B.Tech
4      John     Doe     john@gmail.com        M.Tech
6    Neeraj   Yadav   neeraj@gmail.com           BSc
2      Ravi   Singh     ravi@gmail.com          B.A.
9   Saurabh  Maurya  saurabh@gmail.com           BCA
5    Shivam    Bind   shivam@gmail.com          M.A.
7  Shivansh   Singh     shiv@gmail.com           BCA
0     Vijay   Yadav    vijay@gmail.com           BSc

In [6]:
df.sort_values('first', ascending=False)

      first    last              email qualification
0     Vijay   Yadav    vijay@gmail.com           BSc
7  Shivansh   Singh     shiv@gmail.com           BCA
5    Shivam    Bind   shivam@gmail.com          M.A.
9   Saurabh  Maurya  saurabh@gmail.com           BCA
2      Ravi   Singh     ravi@gmail.com          B.A.
6    Neeraj   Yadav   neeraj@gmail.com           BSc
4      John     Doe     john@gmail.com        M.Tech
3     Anand     Pal    anand@gmail.com        B.Tech
8     Akash   Singh    akash@gmail.com           LLB
1  Abhishek   Yadav     abhi@gmail.com           BCA

In [7]:
df.sort_values(['first', 'last'])

      first    last              email qualification
1  Abhishek   Yadav     abhi@gmail.com           BCA
8     Akash   Singh    akash@gmail.com           LLB
3     Anand     Pal    anand@gmail.com        B.Tech
4      John     Doe     john@gmail.com        M.Tech
6    Neeraj   Yadav   neeraj@gmail.com           BSc
2      Ravi   Singh     ravi@gmail.com          B.A.
9   Saurabh  Maurya  saurabh@gmail.com           BCA
5    Shivam    Bind   shivam@gmail.com          M.A.
7  Shivansh   Singh     shiv@gmail.com           BCA
0     Vijay   Yadav    vijay@gmail.com           BSc

In [8]:
# First name in descending order and last name in ascending order 
df.sort_values(by=['first', 'last'], ascending=[False, True])

      first    last              email qualification
0     Vijay   Yadav    vijay@gmail.com           BSc
7  Shivansh   Singh     shiv@gmail.com           BCA
5    Shivam    Bind   shivam@gmail.com          M.A.
9   Saurabh  Maurya  saurabh@gmail.com           BCA
2      Ravi   Singh     ravi@gmail.com          B.A.
6    Neeraj   Yadav   neeraj@gmail.com           BSc
4      John     Doe     john@gmail.com        M.Tech
3     Anand     Pal    anand@gmail.com        B.Tech
8     Akash   Singh    akash@gmail.com           LLB
1  Abhishek   Yadav     abhi@gmail.com           BCA

In [9]:
# Sorting by index 
df.sort_index()

      first    last              email qualification
0     Vijay   Yadav    vijay@gmail.com           BSc
1  Abhishek   Yadav     abhi@gmail.com           BCA
2      Ravi   Singh     ravi@gmail.com          B.A.
3     Anand     Pal    anand@gmail.com        B.Tech
4      John     Doe     john@gmail.com        M.Tech
5    Shivam    Bind   shivam@gmail.com          M.A.
6    Neeraj   Yadav   neeraj@gmail.com           BSc
7  Shivansh   Singh     shiv@gmail.com           BCA
8     Akash   Singh    akash@gmail.com           LLB
9   Saurabh  Maurya  saurabh@gmail.com           BCA

In [10]:
df['last'].sort_values()

5      Bind
4       Doe
9    Maurya
3       Pal
2     Singh
7     Singh
8     Singh
0     Yadav
1     Yadav
6     Yadav
Name: last, dtype: object

In [11]:
df = pd.read_csv('data/survey_results_public.csv')

In [12]:
df

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,...,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73263,73264,I am a developer by profession,"Employed, full-time",Fully remote,Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Udemy,8,...,30-60 minutes a day,Less than 15 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Too long,Easy,NaN
73264,73265,I am a developer by profession,"Employed, full-time",Full in-person,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy;Udacity,6,...,15-30 minutes a day,60-120 minutes a day,Very long,None of these,No,Yes,Yes,Too long,Easy,NaN
73265,73266,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Programming Games;Stac...,Udemy;Codecademy;Pluralsight;edX,42,...,30-60 minutes a day,60-120 minutes a day,Just right,None of these,No,No,No,Appropriate in length,Easy,NaN
73266,73267,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training,NaN,NaN,50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
73267,73268,"I used to be a developer by profession, but no...","Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Udemy;Pluralsight,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN

In [13]:
df.sort_values(by=['Country', 'CompTotal'], ascending=[True, False], inplace=True)

In [14]:
df[['Country', 'CompTotal']].head(50)

           Country   CompTotal
6891   Afghanistan  55000000.0
38512  Afghanistan   1200000.0
43639  Afghanistan    700000.0
43690  Afghanistan    100000.0
2448   Afghanistan     40000.0
6242   Afghanistan     40000.0
23223  Afghanistan     40000.0
49273  Afghanistan      6000.0
55665  Afghanistan       200.0
3886   Afghanistan         1.0
5464   Afghanistan         1.0
6776   Afghanistan         1.0
17469  Afghanistan         1.0
2737   Afghanistan         0.0
67666  Afghanistan         0.0
1959   Afghanistan         NaN
3641   Afghanistan         NaN
3775   Afghanistan         NaN
4502   Afghanistan         NaN
7944   Afghanistan         NaN
8890   Afghanistan         NaN
10233  Afghanistan         NaN
10910  Afghanistan         NaN
13851  Afghanistan         NaN
15607  Afghanistan         NaN
17038  Afghanistan         NaN
19201  Afghanistan         NaN
21765  Afghanistan         NaN
22876  Afghanistan         NaN
23161  Afghanistan         NaN
24812  Afghanistan         NaN
25962  Afghanistan         NaN
26617  Afghanistan         NaN
28434  Afghanistan         NaN
28582  Afghanistan         NaN
29704  Afghanistan         NaN
30040  Afghanistan         NaN
30850  Afghanistan         NaN
32132  Afghanistan         NaN
33328  Afghanistan         NaN
33428  Afghanistan         NaN
34043  Afghanistan         NaN
42122  Afghanistan         NaN
42870  Afghanistan         NaN
46025  Afghanistan         NaN
46422  Afghanistan         NaN
48959  Afghanistan         NaN
51188  Afghanistan         NaN
51547  Afghanistan         NaN
53960  Afghanistan         NaN

In [15]:
df['CompTotal'].nlargest(10)

35786    9.000000e+56
3068     1.000000e+52
70597    1.000000e+22
17567    1.000000e+15
19244    5.000000e+12
24640    1.500070e+12
31190    1.000000e+12
71603    9.363220e+09
34411    7.200000e+09
49874    6.438169e+09
Name: CompTotal, dtype: float64

In [16]:
df.nlargest(10, 'ConvertedCompYearly')

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,...,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
40304,40305,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Full in-person,Freelance/contract work,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Blogs;Stack Overflow;Online books;Video-based ...,NaN,Less than 1 year,...,60-120 minutes a day,60-120 minutes a day,Very long,Innersource initiative;DevOps function;Develop...,Yes,Yes,Yes,Appropriate in length,Easy,50000000.0
201,202,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Bootstrapping a business,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy;edX,9,...,30-60 minutes a day,Less than 15 minutes a day,Somewhat long,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,44790396.0
62026,62027,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Written Tutorials;Video-based Online Courses;O...,NaN,6,...,60-120 minutes a day,30-60 minutes a day,Somewhat long,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Too long,Neither easy nor difficult,35000000.0
70522,70523,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects;Freel...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Udemy;Pluralsight;Udacity;Other,22,...,30-60 minutes a day,Less than 15 minutes a day,Somewhat short,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Appropriate in length,Easy,32500000.0
61043,61044,I am a developer by profession,I prefer not to say,NaN,NaN,Primary/elementary school,On the job training;Online Courses or Certific...,NaN,Skillsoft,Less than 1 year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,28853768.0
18922,18923,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member...,NaN,Coursera;edX;Udacity,36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,22500000.0
62223,62224,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Friend or family member;Other online resources...,Technical documentation;Blogs;Stack Overflow;O...,NaN,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,22500000.0
66495,66496,I am a developer by profession,"Employed, full-time",Fully remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Other,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,18000000.0
1290,1291,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Other doctoral degree (Ph.D., Ed.D., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Coursera;Pluralsight;edX,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,15000000.0
24163,24164,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Freelance/contract work,Some college/university study without earning ...,Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,NaN,12,...,30-60 minutes a day,30-60 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,No,Appropriate in length,Easy,15000000.0

In [17]:
df.nsmallest(10, 'ConvertedCompYearly')

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,...,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
19912,19913,"I am not primarily a developer, but I write co...",I prefer not to say,NaN,NaN,Primary/elementary school,Books / Physical media,NaN,NaN,13,...,15-30 minutes a day,30-60 minutes a day,Very long,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,1.0
39915,39916,I am a developer by profession,"Employed, full-time;Independent contractor, fr...",Fully remote,Freelance/contract work;School or academic work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Online Courses or Certific...,NaN,Udemy;Pluralsight,15,...,60-120 minutes a day,Over 120 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Too long,Neither easy nor difficult,1.0
65742,65743,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects;Freel...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Blogs;Written Tutorials;Stack Overflow;Video-b...,Coursera;Udemy;Codecademy;Udacity,8,...,15-30 minutes a day,30-60 minutes a day,Somewhat short,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,1.0
64366,64367,"I am not primarily a developer, but I write co...","Employed, full-time",Fully remote,Hobby;Other (please specify):,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Video-based Onli...,Coursera;Udemy;Codecademy,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,1.0
52005,52006,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Bootstrapping a business;Freelance/contr...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc)",NaN,NaN,7,...,30-60 minutes a day,15-30 minutes a day,Very short,None of these,Yes,Yes,Yes,Appropriate in length,Easy,1.0
36435,36436,I am a developer by profession,"Employed, full-time",Full in-person,Hobby,"Associate degree (A.A., A.S., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow,NaN,14,...,15-30 minutes a day,15-30 minutes a day,Just right,Automated testing,Yes,No,No,Too long,Difficult,3.0
6123,6124,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Secondary school (e.g. American high school, G...","Books / Physical media;School (i.e., Universit...",NaN,NaN,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,3.0
32332,32333,I am a developer by profession,"Employed, full-time;Independent contractor, fr...",Fully remote,Hobby;Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,NaN,12,...,15-30 minutes a day,15-30 minutes a day,Just right,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Appropriate in length,Easy,3.0
2376,2377,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Udemy;edX;Other,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,4.0
27980,27981,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects;Freel...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs,NaN,10,...,30-60 minutes a day,Less than 15 minutes a day,Just right,Continuous integration (CI) and (more often) c...,No,No,Yes,Too long,Neither easy nor difficult,4.0